// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// // This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;


// @ts-check

const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'module1/intro',
        'module1/ros2-architecture',
        'module1/cli-tools',
        'module1/packages-workspaces',
        'module1/client-libraries',
        'module1/data-types-transformations',
        'module1/launch-files',
        'module1/lab1',
        'module1/lab2'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Robotics Simulation',
      items: [
        'module2/intro',
        'module2/simulation-environments',
        'module2/robot-description',
        'module2/ros-simulation',
        'module2/physics-sensors',
        'module2/kinematics',
        'module2/lab3',
        'module2/lab4'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      items: [
        'module3/intro',
        'module3/perception',
        'module3/slam',
        'module3/navigation',
        'module3/path-planning',
        'module3/manipulation',
        'module3/state-estimation',
        'module3/lab5',
        'module3/lab6'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Models',
      items: [
        'module4/intro',
        'module4/large-language-models',
        'module4/vision-language-models',
        'module4/visual-language-action',
        'module4/natural-language-understanding',
        'module4/action-generation',
        'module4/case-studies-ethics',
        'module4/lab7',
        'module4/lab8'
      ],
    },
    {
      type: 'category',
      label: 'Cross-Cutting Topics',
      items: [
        'integration-navigation',
        'styling-guidelines',
        'quality-assurance'
      ],
    },
  ],
};

module.exports = sidebars;